name: Update ACI on new image

on:
  workflow_dispatch:  # puoi anche usare un webhook o un trigger da ACR

jobs:
  update-aci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete existing ACI
        run: |
          az container delete --name ${{ secrets.ACI_NAME }} --resource-group ${{ secrets.ACI_RG }} --yes

      - name: Recreate ACI with latest image
        run: |
          az container create --name ${{ secrets.ACI_NAME }} --resource-group ${{ secrets.ACI_RG }} --image ${{ secrets.ACI_IMAGE }} --registry-login-server conregistry12710.azurecr.io --dns-name-label lab5demo --ports 80
